#!/usr/bin/env bash
#
# Copyright 2013-2018 Axel Huebl, Rene Widera, Richard Pausch
#
# This file is part of PIConGPU.
#
# PIConGPU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PIConGPU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIConGPU.
# If not, see <http://www.gnu.org/licenses/>.
#

#
# generic compile options
#

################################################################################
# add presets here
#   - default: index 0
#   - start with zero index
#   - increase by 1, no gaps

flags[0]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=1.0e-5'" 
flags[1]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=1.0e-4'" 
flags[2]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=1.0e-3'" 
flags[3]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=1.4e-5'" 
flags[4]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=1.4e-4'" 
flags[5]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=1.4e-3'" 
flags[6]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=2.0e-5'" 
flags[7]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=2.0e-4'" 
flags[8]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=2.0e-3'" 
flags[9]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=3.2e-5'" 
flags[10]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=3.2e-4'" 
flags[11]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=3.2e-3'" 
flags[12]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=5.0e-5'" 
flags[13]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=5.0e-4'" 
flags[14]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=5.0e-3'" 
flags[15]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=7.1e-5'" 
flags[16]="-DPARAM_OVERWRITES:LIST='-DPARAM_THICKNESS=0.09;-DPARAM_PPC=18u;-DPARAM_INT3=7.1e-4'" 

################################################################################
# execution

case "$1" in
    -l)  echo ${#flags[@]}
         ;;
    -ll) for f in "${flags[@]}"; do echo $f; done
         ;;
    *)   echo -n ${flags[$1]}
         ;;
esac
